### ISSUE TITLE
Im getting a couple of errors while attempting to build

### ISSUE THREAD

**Issue by SightDev** [bigbeawr/csgo-cheat#1]
![image](https://user-images.githubusercontent.com/107509465/179890758-3d3b9aa1-17dd-41c2-9bdf-a19e7c4ffada.png)

**Comment by bigbeawr** [comment]
Ensure that you are building in Debug x86 mode. This should fix the issue and build the dll file in the output/debug directory. 
![image](https://user-images.githubusercontent.com/74503398/180060823-d3e508bf-561b-48c1-b19d-1de9a62975a0.png)
